remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: [Justin's Github Repository]
description: [This is my repository for the class Intro to Digital Humanities at the University of Pennsylvania.]
