remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: [Justin's Github Repository]
description: [Explore my projects to learn about my experiences in research and the Digital Humanities!]
